### ISSUE TITLE
Query recommendations based on user id

### ISSUE THREAD

**Issue by lililin629** [CSCI-GA-2820-SU23-001/recommendations#35]
**As a** Marketing Manager
**I need** the ability to query for recommendations assigned to particular users
**So that** I collect data and perform action routes

### Details and Assumptions
* We will employ PostgreSQL
* Assuming List API is already implemented

 ### Acceptance Criteria  
 ```gherkin
Given our service is running
When I search for recommendations querying based on particular user ID
Then the user's recommendations are returned
```

**Comment by lililin629** [comment]
This was done as part of #8 in sprint1.

**Comment by saiteja-siddana** [comment]
Also handled the wrong data type in query parameters in the new PR.
